/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Tue Aug 14 17:46:37 2018. */

#ifndef PB_EOS_PROTO_EOS_PB_H_INCLUDED
#define PB_EOS_PROTO_EOS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _eos_get_pubkey_req_parameter_t {
    char key_path[51];
/* @@protoc_insertion_point(struct:eos_get_pubkey_req_parameter_t) */
} eos_get_pubkey_req_parameter_t;

typedef struct _eos_get_pubkey_res_parameter_t {
    char pubkey[61];
/* @@protoc_insertion_point(struct:eos_get_pubkey_res_parameter_t) */
} eos_get_pubkey_res_parameter_t;

typedef PB_BYTES_ARRAY_T(7900) eos_transaction_req_parameter_t_unsigned_tx_t;
typedef struct _eos_transaction_req_parameter_t {
    eos_transaction_req_parameter_t_unsigned_tx_t unsigned_tx;
    char key_path[51];
/* @@protoc_insertion_point(struct:eos_transaction_req_parameter_t) */
} eos_transaction_req_parameter_t;

typedef PB_BYTES_ARRAY_T(8000) eos_transaction_res_parameter_t_signed_tx_t;
typedef struct _eos_transaction_res_parameter_t {
    eos_transaction_res_parameter_t_signed_tx_t signed_tx;
/* @@protoc_insertion_point(struct:eos_transaction_res_parameter_t) */
} eos_transaction_res_parameter_t;

/* Default values for struct fields */

/* Initializer values for message structs */
#define eos_transaction_req_parameter_t_init_default {{0, {0}}, ""}
#define eos_transaction_res_parameter_t_init_default {{0, {0}}}
#define eos_get_pubkey_req_parameter_t_init_default {""}
#define eos_get_pubkey_res_parameter_t_init_default {""}
#define eos_transaction_req_parameter_t_init_zero {{0, {0}}, ""}
#define eos_transaction_res_parameter_t_init_zero {{0, {0}}}
#define eos_get_pubkey_req_parameter_t_init_zero {""}
#define eos_get_pubkey_res_parameter_t_init_zero {""}

/* Field tags (for use in manual encoding/decoding) */
#define eos_get_pubkey_req_parameter_t_key_path_tag 2
#define eos_get_pubkey_res_parameter_t_pubkey_tag 1
#define eos_transaction_req_parameter_t_unsigned_tx_tag 1
#define eos_transaction_req_parameter_t_key_path_tag 10
#define eos_transaction_res_parameter_t_signed_tx_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t eos_transaction_req_parameter_t_fields[3];
extern const pb_field_t eos_transaction_res_parameter_t_fields[2];
extern const pb_field_t eos_get_pubkey_req_parameter_t_fields[2];
extern const pb_field_t eos_get_pubkey_res_parameter_t_fields[2];

/* Maximum encoded size of messages (where known) */
#define eos_transaction_req_parameter_t_size     7956
#define eos_transaction_res_parameter_t_size     8003
#define eos_get_pubkey_req_parameter_t_size      53
#define eos_get_pubkey_res_parameter_t_size      63

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define PROTO_EOS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
